name: CI Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:
        
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: .                # Define o contexto como o diretório atual
          file: ./Dockerfile         # Certifique-se de que o Dockerfile está no root do projeto
          tags: ${{ secrets.DOCKER_USERNAME }}/catalog:latest
          
      - name: Upload Maven Artifact
        uses: actions/upload-artifact@v3
        with:
          name: packaged-application
          path: target/*.jar
